### ISSUE TITLE
Getting error about NODE_MODULE_VERSION incompatibility of murmurhash-native on node 10 

### ISSUE THREAD

**Issue by GermanGorodnev** [mapbox/carmen#936]
### Context

Trying to perform install via yarn inside docker using node:10 image. Installation goes without any errors, but once the app runs, I get the following error
```
internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/app/node_modules/murmurhash-native/lib/Release/murmurhash.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/node_modules/murmurhash-native/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```
I assume this is because yarn pulls precompiled dependencies which are not suitable for node10. Is there something that could be done to make it running?

package.json:  
```
{
  "name": "mapbox_service",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node src"
  },
  "dependencies": {
    "@mapbox/carmen": "27.0.0"
  },
  "author": "",
  "license": "ISC"
}
```

Dockerfile:
```
FROM node:10

USER root
RUN rm -rf node_modules
RUN mkdir -p /app/node_modules
WORKDIR /app

COPY "./package.json" ./

RUN apt-get update
RUN apt-get install -y \
    build-essential \
    curl
RUN apt-get update

# Get Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH=/usr/local/cargo/bin:$PATH
RUN yarn --ignore-engines
COPY --chown=node:node src .
EXPOSE 8080

CMD [ "node", "src" ]
```

docker-compose.yaml
```
version: "3.1"
services:
  nodejs:
    image: "node:10"
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    expose:
      - "3080"
    ports:
      - "3080:3080"
    networks:
      - app-network
    environment:
      - PORT=3080
    command: "node src"

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:  
```

@mapbox/search
